server.port=8080
server.servlet.context-path=/savr-api
spring.datasource.url=jdbc:mysql://${DB_HOST}:3306/savr?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

scraping.user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
scraping.referrer=http://www.google.com
scraping.timeout=12000
scraping.ignore-content-type=true
scraping.follow-redirects=true

administrator.phoneNumber=${ADMIN_PHONE_NUMBER}

alert.dayStartCron=0 0 16 ? * *
alert.frequentCron=0 0,15,30,45 3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22 ? * *

plaid.clientId=${PLAID_CLIENT_ID}
plaid.secret=${PLAID_SECRET}
plaid.accessToken=${PLAID_ACCESS_TOKEN}

twilio.accoundSid=${TWILIO_ACCOUNT_SID}
twilio.authToken=${TWILIO_AUTH_TOKEN}
twilio.phoneNumber=${TWILIO_PHONE_NUMBER}
twilio.transactionsToMessageLimit=5
twilio.transactionNameContentLimit=10

binance.apiHost=https://api.binance.us/
binance.apiKey=${BINANCE_API_KEY}
binance.apiSecret=${BINANCE_API_SECRET}

binance-alert.significantPriceChangePercent=10

market-stack.apiHost=http://api.marketstack.com/v1/
market-stack.apiKey=${MARKET_STACK_API_KEY}
market-stack.available-exchanges=XNAS

amazon.url=https://www.amazon.com

ebay.apiHost=https://svcs.ebay.com/

walmart.url=https://www.walmart.com

fandango.apiKey=${FANDANGO_API_KEY}
fandango.secret=${FANDANGO_SECRET}

value-serp.api-url=https://api.valueserp.com
value-serp.api-key=${VALUE_SERP_API_KEY}
